<a href="https://colab.research.google.com/github/Mohan0051/Mohan/blob/main/pandas_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive

In [ ]:
#read data from a csv file
df=pd.read_csv("/content/bike sales data.csv")
#read data from a excel file
#pd.read_excel()
#read data from a sql database
#pd.read_sql()
#read data from a json file
c=df
c

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,12/1/2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
1,261695,12/1/2021,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,12/2/2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,12/3/2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,261778,12/22/2021,22.0,December,2021,41,Adults (35-64),M,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
85,261779,12/23/2021,23.0,December,2021,30,Young Adults (25-34),F,United States,Oregon,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
86,261780,12/23/2021,23.0,December,2021,31,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
87,261781,12/23/2021,23.0,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1.0,$295.00,$540.00,$245.00,$295.00,$540.00
88,261782,12/24/2021,24.0,December,2021,38,Adults (35-64),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Black, 42",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"

In [ ]:
#display the first and last n rows of dataframe
d=df.head()
d

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,12/1/2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
1,261695,12/1/2021,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,12/2/2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,12/3/2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00"

In [ ]:
#last rows
df.tail()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
84,261778,12/22/2021,22.0,December,2021,41,Adults (35-64),M,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
85,261779,12/23/2021,23.0,December,2021,30,Young Adults (25-34),F,United States,Oregon,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
86,261780,12/23/2021,23.0,December,2021,31,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
87,261781,12/23/2021,23.0,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1.0,$295.00,$540.00,$245.00,$295.00,$540.00
88,261782,12/24/2021,24.0,December,2021,38,Adults (35-64),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Black, 42",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"

In [ ]:
#display a concise summary of a dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_Order #        89 non-null     int64
 1   Date                 89 non-null     object
 2   Day                  88 non-null     float64
 3   Month                89 non-null     object
 4   Year                 89 non-null     int64
 5   Customer_Age         89 non-null     int64
 6   Age_Group            88 non-null     object
 7   Customer_Gender      89 non-null     object
 8   Country              89 non-null     object
 9   State                89 non-null     object
 10  Product_Category     89 non-null     object
 11  Sub_Category         89 non-null     object
 12  Product_Description  88 non-null     object
 13  Order_Quantity       88 non-null     float64
 14   Unit_Cost           89 non-null     object
 15   Unit_Price          89 non-null     object
 16   Profit              89 non-null     object
 17   Cost                89 non-null     object
 18  Revenue              89 non-null     object
dtypes: float64(2), int64(3), object(14)
memory usage: 13.3+ KB

In [ ]:
#generate descriptive satistics
df.describe()

       Sales_Order #        Day    Year  Customer_Age  Order_Quantity
count      89.000000  88.000000    89.0     89.000000       88.000000
mean   261738.067416  13.534091  2021.0     34.202247        2.125000
std        25.729713   6.391353     0.0      8.090651        1.239322
min    261695.000000   1.000000  2021.0     17.000000        1.000000
25%    261716.000000   8.750000  2021.0     30.000000        1.000000
50%    261738.000000  13.500000  2021.0     35.000000        2.000000
75%    261760.000000  19.000000  2021.0     38.000000        3.000000
max    261782.000000  24.000000  2021.0     63.000000        4.000000

In [ ]:
#returns the dimension of the dataframe
df.shape

(89, 19)

In [ ]:
#returns the column labels
df.columns

Index(['Sales_Order #', 'Date', 'Day', 'Month', 'Year', 'Customer_Age',
       'Age_Group', 'Customer_Gender', 'Country', 'State', 'Product_Category',
       'Sub_Category', 'Product_Description', 'Order_Quantity', ' Unit_Cost ',
       ' Unit_Price ', ' Profit ', ' Cost ', 'Revenue'],
      dtype='object')

In [ ]:
#returns the datatype of each column
df.dtypes

Sales_Order #            int64
Date                    object
Day                    float64
Month                   object
Year                     int64
Customer_Age             int64
Age_Group               object
Customer_Gender         object
Country                 object
State                   object
Product_Category        object
Sub_Category            object
Product_Description     object
Order_Quantity         float64
 Unit_Cost              object
 Unit_Price             object
 Profit                 object
 Cost                   object
Revenue                 object
dtype: object

In [ ]:
#selecting and indexing
#selecting a single column
df['Year']

0     2021
1     2021
2     2021
3     2021
4     2021
      ...
84    2021
85    2021
86    2021
87    2021
88    2021
Name: Year, Length: 89, dtype: int64

In [ ]:
#selecting multi column
df[['Year','Date']]

    Year        Date
0   2021   12/1/2021
1   2021   12/1/2021
2   2021   12/2/2021
3   2021   12/2/2021
4   2021   12/3/2021
..   ...         ...
84  2021  12/22/2021
85  2021  12/23/2021
86  2021  12/23/2021
87  2021  12/23/2021
88  2021  12/24/2021

[89 rows x 2 columns]

In [ ]:
#acess a group of rows and column by labels
df.loc[0]

Sales_Order #                          261695
Date                                12/1/2021
Day                                       1.0
Month                                December
Year                                     2021
Customer_Age                               39
Age_Group                      Adults (35-64)
Customer_Gender                             F
Country                         United States
State                              California
Product_Category                        Bikes
Sub_Category                   Mountain Bikes
Product_Description    Mountain-200 Black, 46
Order_Quantity                            4.0
 Unit_Cost                         $1,252.00
 Unit_Price                        $2,295.00
 Profit                            $4,172.00
 Cost                              $5,008.00
Revenue                            $9,180.00
Name: 0, dtype: object

In [ ]:
#acess a group of rows and column by integer position
df.iloc[1,2]

1.0

In [ ]:
#filtering data
#filter rows based on condition
df[df['Day']>1.0]

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,12/2/2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,12/3/2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00"
5,261700,12/3/2021,3.0,December,2021,24,Youth (<25),F,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
6,261701,12/3/2021,3.0,December,2021,37,Adults (35-64),M,United States,Washington,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,261778,12/22/2021,22.0,December,2021,41,Adults (35-64),M,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
85,261779,12/23/2021,23.0,December,2021,30,Young Adults (25-34),F,United States,Oregon,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
86,261780,12/23/2021,23.0,December,2021,31,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
87,261781,12/23/2021,23.0,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1.0,$295.00,$540.00,$245.00,$295.00,$540.00
88,261782,12/24/2021,24.0,December,2021,38,Adults (35-64),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Black, 42",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"

In [ ]:
#handling missing data
#checking for missing values
df.isnull()
df.notnull()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
85,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
86,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
87,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
88,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
#drop rows with missing values
df.dropna()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,12/1/2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
1,261695,12/1/2021,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,12/2/2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,12/3/2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,261778,12/22/2021,22.0,December,2021,41,Adults (35-64),M,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
85,261779,12/23/2021,23.0,December,2021,30,Young Adults (25-34),F,United States,Oregon,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
86,261780,12/23/2021,23.0,December,2021,31,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
87,261781,12/23/2021,23.0,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1.0,$295.00,$540.00,$245.00,$295.00,$540.00
88,261782,12/24/2021,24.0,December,2021,38,Adults (35-64),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Black, 42",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"

In [ ]:
#fill missingvalues
df.fillna(10)

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,12/1/2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
1,261695,12/1/2021,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,12/2/2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,12/3/2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,261778,12/22/2021,22.0,December,2021,41,Adults (35-64),M,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
85,261779,12/23/2021,23.0,December,2021,30,Young Adults (25-34),F,United States,Oregon,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
86,261780,12/23/2021,23.0,December,2021,31,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
87,261781,12/23/2021,23.0,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1.0,$295.00,$540.00,$245.00,$295.00,$540.00
88,261782,12/24/2021,24.0,December,2021,38,Adults (35-64),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Black, 42",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"

In [ ]:
d=c.copy()
d

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,12/1/2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
1,261695,12/1/2021,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,12/2/2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,12/3/2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,261778,12/22/2021,22.0,December,2021,41,Adults (35-64),M,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
85,261779,12/23/2021,23.0,December,2021,30,Young Adults (25-34),F,United States,Oregon,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
86,261780,12/23/2021,23.0,December,2021,31,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
87,261781,12/23/2021,23.0,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1.0,$295.00,$540.00,$245.00,$295.00,$540.00
88,261782,12/24/2021,24.0,December,2021,38,Adults (35-64),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Black, 42",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"

In [ ]:
#manipulating data
#group dataframe using a series of column
grouped = df.groupby('Country')

# Print the groups
for name, group in grouped:
    print(name)
    print(group)

 United States
   Sales_Order #       Date  Day     Month  Year  Customer_Age  \
2         261697  12/2/2021  2.0  December  2021            37

        Age_Group Customer_Gender         Country       State  \
2  Adults (35-64)               M   United States  California

  Product_Category    Sub_Category        Product_Description  Order_Quantity  \
2            Bikes  Mountain Bikes  Mountain-400-W Silver, 46             2.0

   Unit_Cost   Unit_Price    Profit      Cost      Revenue
2    $420.00      $769.00   $698.00   $840.00   $1,538.00
Australia
    Sales_Order #        Date   Day     Month  Year  Customer_Age  \
3          261698   12/2/2021   2.0  December  2021            31
8          261702   12/4/2021   4.0  December  2021            31
11         261705   12/5/2021   5.0  December  2021            35
15         261709   12/6/2021   6.0  December  2021            36
19         261713   12/8/2021   8.0  December  2021            19
23         261717   12/9/2021   9.0  December  2021            33
26         261720  12/10/2021  10.0  December  2021            40
30         261724  12/10/2021  10.0  December  2021            38
32         261726  12/11/2021  11.0  December  2021            41
36         261730  12/12/2021  12.0  December  2021            36
38         261732  12/12/2021  12.0  December  2021            34
39         261733  12/12/2021  12.0  December  2021            35
41         261735  12/13/2021  13.0  December  2021            32
47         261741  12/14/2021  14.0  December  2021            32
49         261743  12/16/2021  16.0  December  2021            33
50         261744  12/16/2021  16.0  December  2021            38
53         261747  12/17/2021  17.0  December  2021            31
55         261749  12/18/2021  18.0  December  2021            35
63         261757  12/19/2021  19.0  December  2021            19
68         261762  12/19/2021  19.0  December  2021            63
69         261763  12/19/2021  19.0  December  2021            18
72         261766  12/20/2021  20.0  December  2021            33
73         261767  12/20/2021  20.0  December  2021            57
75         261769  12/20/2021  20.0  December  2021            35
76         261770  12/20/2021  20.0  December  2021            35
81         261775  12/22/2021  22.0  December  2021            19
88         261782  12/24/2021  24.0  December  2021            38

               Age_Group Customer_Gender    Country            State  \
3   Young Adults (25-34)               F  Australia  New South Wales
8   Young Adults (25-34)               F  Australia  New South Wales
11        Adults (35-64)               F  Australia       Queensland
15                   NaN               M  Australia  New South Wales
19           Youth (<25)               F  Australia  New South Wales
23  Young Adults (25-34)               F  Australia         Victoria
26        Adults (35-64)               M  Australia  New South Wales
30        Adults (35-64)               M  Australia  New South Wales
32        Adults (35-64)               F  Australia  New South Wales
36        Adults (35-64)               F  Australia  New South Wales
38  Young Adults (25-34)               M  Australia  New South Wales
39        Adults (35-64)               F  Australia         Victoria
41  Young Adults (25-34)               F  Australia       Queensland
47  Young Adults (25-34)               F  Australia         Victoria
49  Young Adults (25-34)               F  Australia  New South Wales
50        Adults (35-64)               M  Australia  New South Wales
53  Young Adults (25-34)               M  Australia  New South Wales
55        Adults (35-64)               F  Australia  New South Wales
63           Youth (<25)               F  Australia         Victoria
68        Adults (35-64)               F  Australia       Queensland
69           Youth (<25)               M  Australia  South Australia
72  Young Adults (25-34)               F  Australia         Victoria
73        Adults (35-64)               M  Australia       Queensland
75        Adults (35-64)               F  Australia       Queensland
76        Adults (35-64)               M  Australia         Victoria
81           Youth (<25)               F  Australia  New South Wales
88        Adults (35-64)               M  Australia       Queensland

   Product_Category    Sub_Category        Product_Description  \
3             Bikes  Mountain Bikes  Mountain-400-W Silver, 42
8             Bikes  Mountain Bikes  Mountain-400-W Silver, 42
11            Bikes  Mountain Bikes    Mountain-200 Silver, 38
15            Bikes  Mountain Bikes     Mountain-200 Black, 42
19            Bikes  Mountain Bikes    Mountain-500 Silver, 42
23            Bikes  Mountain Bikes     Mountain-100 Black, 38
26            Bikes  Mountain Bikes     Mountain-200 Black, 42
30            Bikes  Mountain Bikes     Mountain-200 Black, 38
32            Bikes  Mountain Bikes  Mountain-400-W Silver, 38
36            Bikes  Mountain Bikes    Mountain-200 Silver, 42
38            Bikes  Mountain Bikes     Mountain-200 Black, 38
39            Bikes  Mountain Bikes    Mountain-200 Silver, 42
41            Bikes  Mountain Bikes    Mountain-200 Silver, 42
47            Bikes  Mountain Bikes  Mountain-400-W Silver, 46
49            Bikes  Mountain Bikes     Mountain-200 Black, 38
50            Bikes  Mountain Bikes     Mountain-200 Black, 38
53            Bikes  Mountain Bikes  Mountain-400-W Silver, 42
55            Bikes  Mountain Bikes    Mountain-500 Silver, 42
63            Bikes  Mountain Bikes     Mountain-500 Black, 44
68            Bikes  Mountain Bikes     Mountain-200 Black, 46
69            Bikes  Mountain Bikes     Mountain-500 Black, 40
72            Bikes  Mountain Bikes     Mountain-100 Black, 38
73            Bikes  Mountain Bikes     Mountain-200 Black, 46
75            Bikes  Mountain Bikes    Mountain-200 Silver, 38
76            Bikes  Mountain Bikes    Mountain-200 Silver, 38
81            Bikes  Mountain Bikes    Mountain-500 Silver, 42
88            Bikes  Mountain Bikes     Mountain-200 Black, 42

    Order_Quantity  Unit_Cost   Unit_Price      Profit        Cost   \
3              1.0    $420.00      $769.00     $349.00     $420.00
8              4.0    $420.00        $0.00   $1,396.00   $1,680.00
11             1.0  $1,266.00    $2,320.00   $1,054.00   $1,266.00
15             1.0  $1,252.00    $2,295.00   $1,043.00   $1,252.00
19             4.0    $308.00      $565.00   $1,028.00   $1,232.00
23             2.0  $1,898.00    $3,375.00   $2,954.00   $3,796.00
26             2.0  $1,252.00    $2,295.00   $2,086.00   $2,504.00
30             1.0  $1,252.00    $2,295.00   $1,043.00   $1,252.00
32             2.0    $420.00      $769.00     $698.00     $840.00
36             4.0  $1,266.00    $2,320.00   $4,216.00   $5,064.00
38             2.0  $1,252.00    $2,295.00   $2,086.00   $2,504.00
39             1.0  $1,266.00    $2,320.00   $1,054.00   $1,266.00
41             3.0  $1,266.00    $2,320.00   $3,162.00   $3,798.00
47             1.0    $420.00      $769.00     $349.00     $420.00
49             2.0  $1,252.00    $2,295.00   $2,086.00   $2,504.00
50             2.0  $1,252.00    $2,295.00   $2,086.00   $2,504.00
53             1.0    $420.00      $769.00     $349.00     $420.00
55             4.0    $308.00      $565.00   $1,028.00   $1,232.00
63             4.0    $295.00      $540.00     $980.00   $1,180.00
68             4.0  $1,252.00    $2,295.00   $4,172.00   $5,008.00
69             2.0    $295.00      $540.00     $490.00     $590.00
72             4.0  $1,898.00    $3,375.00   $5,908.00   $7,592.00
73             4.0  $1,252.00    $2,295.00   $4,172.00   $5,008.00
75             1.0  $1,266.00    $2,320.00   $1,054.00   $1,266.00
76             1.0  $1,266.00    $2,320.00   $1,054.00   $1,266.00
81             1.0    $308.00      $565.00     $257.00     $308.00
88             4.0  $1,252.00    $2,295.00   $4,172.00   $5,008.00

        Revenue
3      $769.00
8        $0.00
11   $2,320.00
15   $2,295.00
19   $2,260.00
23   $6,750.00
26   $4,590.00
30   $2,295.00
32   $1,538.00
36   $9,280.00
38   $4,590.00
39   $2,320.00
41   $6,960.00
47     $769.00
49   $4,590.00
50   $4,590.00
53     $769.00
55   $2,260.00
63   $2,160.00
68   $9,180.00
69   $1,080.00
72  $13,500.00
73   $9,180.00
75   $2,320.00
76   $2,320.00
81     $565.00
88   $9,180.00
Canada
    Sales_Order #        Date   Day     Month  Year  Customer_Age  \
14         261708   12/6/2021   6.0  December  2021            27
20         261714   12/8/2021   8.0  December  2021            30
33         261727  12/11/2021  11.0  December  2021            27
74         261768  12/20/2021  20.0  December  2021            29
83         261777  12/22/2021  22.0  December  2021            27
86         261780  12/23/2021  23.0  December  2021            31

               Age_Group Customer_Gender Country             State  \
14  Young Adults (25-34)               M  Canada  British Columbia
20  Young Adults (25-34)               F  Canada  British Columbia
33  Young Adults (25-34)               M  Canada  British Columbia
74  Young Adults (25-34)               M  Canada  British Columbia
83  Young Adults (25-34)               F  Canada  British Columbia
86  Young Adults (25-34)               F  Canada  British Columbia

   Product_Category    Sub_Category      Product_Description  Order_Quantity  \
14            Bikes  Mountain Bikes   Mountain-200 Black, 46             1.0
20            Bikes  Mountain Bikes  Mountain-200 Silver, 38             4.0
33            Bikes  Mountain Bikes   Mountain-200 Black, 46             1.0
74            Bikes  Mountain Bikes   Mountain-500 Black, 52             3.0
83            Bikes  Mountain Bikes   Mountain-200 Black, 46             1.0
86            Bikes  Mountain Bikes   Mountain-200 Black, 42             1.0

    Unit_Cost   Unit_Price      Profit        Cost      Revenue
14  $1,252.00    $2,295.00   $1,043.00   $1,252.00   $2,295.00
20  $1,266.00    $2,320.00   $4,216.00   $5,064.00   $9,280.00
33  $1,252.00    $2,295.00   $1,043.00   $1,252.00   $2,295.00
74    $295.00      $540.00     $735.00     $885.00   $1,620.00
83  $1,252.00    $2,295.00   $1,043.00   $1,252.00   $2,295.00
86  $1,252.00    $2,295.00   $1,043.00   $1,252.00   $2,295.00
France
    Sales_Order #        Date   Day     Month  Year  Customer_Age  \
31         261725  12/11/2021  11.0  December  2021            24
51         261745  12/16/2021  16.0  December  2021            27
57         261751  12/18/2021  18.0  December  2021            24
60         261754  12/18/2021  18.0  December  2021            26
62         261756  12/19/2021  19.0  December  2021            17
64         261758  12/19/2021  19.0  December  2021            25
77         261771  12/21/2021  21.0  December  2021            26
82         261776  12/22/2021  22.0  December  2021            25

               Age_Group Customer_Gender Country              State  \
31           Youth (<25)               F  France      Seine (Paris)
51  Young Adults (25-34)               F  France     Seine et Marne
57           Youth (<25)               F  France  Seine Saint Denis
60  Young Adults (25-34)               M  France      Seine (Paris)
62           Youth (<25)               M  France               Nord
64  Young Adults (25-34)               M  France      Seine (Paris)
77  Young Adults (25-34)               M  France              Somme
82  Young Adults (25-34)               M  France      Seine (Paris)

   Product_Category    Sub_Category      Product_Description  Order_Quantity  \
31            Bikes  Mountain Bikes   Mountain-200 Black, 38             3.0
51            Bikes  Mountain Bikes  Mountain-200 Silver, 46             1.0
57            Bikes  Mountain Bikes  Mountain-200 Silver, 38             3.0
60            Bikes  Mountain Bikes   Mountain-200 Black, 46             1.0
62            Bikes  Mountain Bikes  Mountain-200 Silver, 46             4.0
64            Bikes  Mountain Bikes   Mountain-200 Black, 38             4.0
77            Bikes  Mountain Bikes  Mountain-200 Silver, 38             3.0
82            Bikes  Mountain Bikes   Mountain-200 Black, 38             1.0

    Unit_Cost   Unit_Price      Profit        Cost      Revenue
31  $1,252.00    $2,295.00   $3,129.00   $3,756.00   $6,885.00
51  $1,266.00    $2,320.00   $1,054.00   $1,266.00   $2,320.00
57  $1,266.00    $2,320.00   $3,162.00   $3,798.00   $6,960.00
60  $1,252.00    $2,295.00   $1,043.00   $1,252.00   $2,295.00
62  $1,266.00    $2,320.00   $4,216.00   $5,064.00   $9,280.00
64  $1,252.00    $2,295.00   $4,172.00   $5,008.00   $9,180.00
77  $1,266.00    $2,320.00   $3,162.00   $3,798.00   $6,960.00
82  $1,252.00    $2,295.00   $1,043.00   $1,252.00   $2,295.00
Germany
    Sales_Order #        Date   Day     Month  Year  Customer_Age  \
10         261704   12/5/2021   NaN  December  2021            42
24         261718   12/9/2021   9.0  December  2021            41
54         261748  12/17/2021  17.0  December  2021            42
56         261750  12/18/2021  18.0  December  2021            38
70         261764  12/19/2021  19.0  December  2021            56
84         261778  12/22/2021  22.0  December  2021            41

         Age_Group Customer_Gender  Country                State  \
10  Adults (35-64)               M  Germany  Nordrhein-Westfalen
24  Adults (35-64)               F  Germany              Hamburg
54  Adults (35-64)               F  Germany  Nordrhein-Westfalen
56  Adults (35-64)               F  Germany  Nordrhein-Westfalen
70  Adults (35-64)               F  Germany               Hessen
84  Adults (35-64)               M  Germany               Hessen

   Product_Category    Sub_Category      Product_Description  Order_Quantity  \
10            Bikes  Mountain Bikes   Mountain-200 Black, 38             4.0
24            Bikes  Mountain Bikes  Mountain-200 Silver, 42             1.0
54            Bikes  Mountain Bikes  Mountain-200 Silver, 46             1.0
56            Bikes  Mountain Bikes  Mountain-200 Silver, 46             4.0
70            Bikes  Mountain Bikes   Mountain-200 Black, 46             2.0
84            Bikes  Mountain Bikes  Mountain-200 Silver, 38             1.0

    Unit_Cost   Unit_Price      Profit        Cost      Revenue
10  $1,252.00    $2,295.00   $4,172.00   $5,008.00   $9,180.00
24  $1,266.00    $2,320.00   $1,054.00   $1,266.00   $2,320.00
54  $1,266.00    $2,320.00   $1,054.00   $1,266.00   $2,320.00
56  $1,266.00    $2,320.00   $4,216.00   $5,064.00   $9,280.00
70  $1,252.00    $2,295.00   $2,086.00   $2,504.00   $4,590.00
84  $1,266.00    $2,320.00   $1,054.00   $1,266.00   $2,320.00
United  States
   Sales_Order #       Date  Day     Month  Year  Customer_Age  \
4         261699  12/3/2021  3.0  December  2021            37

        Age_Group Customer_Gender         Country       State  \
4  Adults (35-64)               F  United  States  California

  Product_Category    Sub_Category     Product_Description  Order_Quantity  \
4            Bikes  Mountain Bikes  Mountain-200 Black, 46             2.0

   Unit_Cost   Unit_Price      Profit    Cost      Revenue
4      $0.00    $2,295.00   $2,086.00   $0.00   $4,590.00
United Kingdom
    Sales_Order #        Date   Day     Month  Year  Customer_Age  \
1          261695   12/1/2021   1.0  December  2021            44
5          261700   12/3/2021   3.0  December  2021            24
13         261707   12/6/2021   6.0  December  2021            23
16         261710   12/6/2021   6.0  December  2021            47
27         261721  12/10/2021  10.0  December  2021            26
43         261737  12/13/2021  13.0  December  2021            44
44         261738  12/13/2021  13.0  December  2021            49
58         261752  12/18/2021  18.0  December  2021            26
78         261772  12/21/2021  21.0  December  2021            23

               Age_Group Customer_Gender         Country    State  \
1         Adults (35-64)               M  United Kingdom  England
5            Youth (<25)               F  United Kingdom  England
13           Youth (<25)               M  United Kingdom  England
16        Adults (35-64)               M  United Kingdom  England
27  Young Adults (25-34)               M  United Kingdom  England
43        Adults (35-64)               F  United Kingdom  England
44        Adults (35-64)               M  United Kingdom  England
58  Young Adults (25-34)               F  United Kingdom  England
78           Youth (<25)               M  United Kingdom  England

   Product_Category    Sub_Category        Product_Description  \
1             Bikes  Mountain Bikes    Mountain-200 Silver, 42
5             Bikes  Mountain Bikes     Mountain-200 Black, 38
13            Bikes  Mountain Bikes  Mountain-400-W Silver, 46
16            Bikes  Mountain Bikes    Mountain-200 Silver, 38
27            Bikes  Mountain Bikes     Mountain-200 Black, 38
43            Bikes  Mountain Bikes     Mountain-200 Black, 38
44            Bikes  Mountain Bikes     Mountain-200 Black, 38
58            Bikes  Mountain Bikes  Mountain-400-W Silver, 42
78            Bikes  Mountain Bikes  Mountain-400-W Silver, 46

    Order_Quantity  Unit_Cost   Unit_Price      Profit        Cost   \
1              1.0  $1,266.00    $2,320.00   $1,054.00   $1,266.00
5              1.0  $1,252.00    $2,295.00   $1,043.00   $1,252.00
13             3.0    $420.00      $769.00   $1,047.00   $1,260.00
16             1.0  $1,266.00    $2,320.00   $1,054.00   $1,266.00
27             1.0  $1,252.00    $2,295.00   $1,043.00   $1,252.00
43             1.0  $1,252.00    $2,295.00   $1,043.00   $1,252.00
44             1.0  $1,252.00    $2,295.00   $1,043.00   $1,252.00
58             3.0    $420.00      $769.00   $1,047.00   $1,260.00
78             2.0    $420.00      $769.00     $698.00     $840.00

       Revenue
1   $2,320.00
5   $2,295.00
13  $2,307.00
16  $2,320.00
27  $2,295.00
43  $2,295.00
44  $2,295.00
58  $2,307.00
78  $1,538.00
United States
    Sales_Order #        Date   Day     Month  Year  Customer_Age  \
0          261695   12/1/2021   1.0  December  2021            39
7          261701   12/3/2021   3.0  December  2021            37
9          261703   12/5/2021   5.0  December  2021            39
12         261706   12/5/2021   5.0  December  2021            37
17         261711   12/7/2021   7.0   Decmber  2021            30
18         261712   12/7/2021   7.0  December  2021            38
21         261715   12/8/2021   8.0  December  2021            39
22         261716   12/8/2021   8.0  December  2021            35
25         261719  12/10/2021  10.0  December  2021            34
28         261722  12/10/2021  10.0  December  2021            34
29         261723  12/10/2021  10.0  December  2021            34
34         261728  12/11/2021  11.0  December  2021            37
35         261729  12/11/2021  11.0  December  2021            38
37         261731  12/12/2021  12.0  December  2021            37
40         261734  12/12/2021  12.0  December  2021            38
42         261736  12/13/2021  13.0  December  2021            40
45         261739  12/14/2021  14.0  December  2021            30
46         261740  12/14/2021  14.0  December  2021            32
48         261742  12/15/2021  15.0  December  2021            29
52         261746  12/17/2021  17.0  December  2021            37
59         261753  12/18/2021  18.0  December  2021            39
61         261755  12/18/2021  18.0  December  2021            36
65         261759  12/19/2021  19.0  December  2021            35
66         261760  12/19/2021  19.0  December  2021            37
67         261761  12/19/2021  19.0  December  2021            39
71         261765  12/19/2021  19.0  December  2021            39
79         261773  12/22/2021  22.0  December  2021            30

In [ ]:
#creating a pivot table
pivot_table=df.pivot_table(values='Country',index='Date',columns='Day')
#displaying a pivot table
pivot_table

<ipython-input-36-c18345b9c7e4>:2: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pivot_table=df.pivot_table(values='Country',index='Date',columns='Day')

Empty DataFrame
Columns: []
Index: [12/1/2021, 12/10/2021, 12/11/2021, 12/12/2021, 12/13/2021, 12/14/2021, 12/15/2021, 12/16/2021, 12/17/2021, 12/18/2021, 12/19/2021, 12/2/2021, 12/20/2021, 12/21/2021, 12/22/2021, 12/23/2021, 12/24/2021, 12/3/2021, 12/4/2021, 12/5/2021, 12/6/2021, 12/7/2021, 12/8/2021, 12/9/2021]

In [ ]:
#soring the dataframe by runtime column in ascending order
#sorting the dataframe by release_year in descending order
sorted_df=df.sort_values(by=['Country','Date'],ascending=[True,False])
#displaying a sorted dataframe
sorted_df

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
23,261717,12/9/2021,9.0,December,2021,33,Young Adults (25-34),F,Australia,Victoria,Bikes,Mountain Bikes,"Mountain-100 Black, 38",2.0,"$1,898.00","$3,375.00","$2,954.00","$3,796.00","$6,750.00"
19,261713,12/8/2021,8.0,December,2021,19,Youth (<25),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-500 Silver, 42",4.0,$308.00,$565.00,"$1,028.00","$1,232.00","$2,260.00"
15,261709,12/6/2021,6.0,December,2021,36,NaN,M,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"
11,261705,12/5/2021,5.0,December,2021,35,Adults (35-64),F,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,261719,12/10/2021,10.0,December,2021,34,Young Adults (25-34),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 42",2.0,"$1,252.00","$2,295.00","$2,086.00","$2,504.00","$4,590.00"
28,261722,12/10/2021,10.0,December,2021,34,Young Adults (25-34),M,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 40",1.0,$295.00,$540.00,$245.00,$295.00,$540.00
29,261723,12/10/2021,10.0,December,2021,34,Young Adults (25-34),F,United States,Washington,Bikes,Mountain Bikes,"Mountain-100 Silver, 44",1.0,"$1,912.00","$3,400.00","$1,488.00","$1,912.00","$3,400.00"
0,261695,12/1/2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
6,261701,12/3/2021,3.0,December,2021,37,Adults (35-64),M,United States,Washington,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00"

In [ ]:
#series
A=[1, 2,3]
y=pd.Series(A, index=["A", "B",5])
print (y)

A    1
B    2
5    3
dtype: int64

In [ ]:
import numpy as np
Df=pd.DataFrame(data=np.array([[1, 2,3], [4, 5,6], [7, 8,9]]), index=[1,2,3], columns=['A', 'B', 'C'])
print(Df)
Df.loc[2]=[60, 50,37]
print(Df)
Df['D']=['0', '1', '2']
print(Df)

   A  B  C
1  1  2  3
2  4  5  6
3  7  8  9
    A   B   C
1   1   2   3
2  60  50  37
3   7   8   9
    A   B   C  D
1   1   2   3  0
2  60  50  37  1
3   7   8   9  2

In [ ]:
print(Df.shape)
print(Df.index)
print(Df.columns)
print(Df.count())
print(Df.info())

(3, 4)
Int64Index([1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D'], dtype='object')
A    3
B    3
C    3
D    3
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 1 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
 3   D       3 non-null      object
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes
None

In [ ]:
print(Df.sum())
print(Df.cumsum())
print(Df.min())
print(Df.describe())
print(Df.mean())
print(Df.median())

A     68
B     60
C     49
D    012
dtype: object
    A   B   C    D
1   1   2   3    0
2  61  52  40   01
3  68  60  49  012
A    1
B    2
C    3
D    0
dtype: object
               A          B          C
count   3.000000   3.000000   3.000000
mean   22.666667  20.000000  16.333333
std    32.470499  26.153394  18.147543
min     1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000
50%     7.000000   8.000000   9.000000
75%    33.500000  29.000000  23.000000
max    60.000000  50.000000  37.000000
A    22.666667
B    20.000000
C    16.333333
D     4.000000
dtype: float64
A    7.0
B    8.0
C    9.0
D    1.0
dtype: float64

In [ ]:
Df['A']=6
print(Df)

   A   B   C  D
1  6   2   3  0
2  6  50  37  1
3  6   8   9  2

In [ ]:
s3=pd.Series([7,-2,3],index=['a','c','d'])
Df+s3

    A   B   C    D   a   c   d
1 NaN NaN NaN  NaN NaN NaN NaN
2 NaN NaN NaN  NaN NaN NaN NaN
3 NaN NaN NaN  NaN NaN NaN NaN